version: 2
jobs:

  test-build-golang-prev:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install linux dependencies - libusb
          command: |
            sudo apt update -q
            sudo apt install -yq libusb-dev libusb-1.0.0-dev
      - run:
          name: Test
          command: |
            go build -mod=vendor
            ./aws-okta version

  dist-windows:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/segmentio/aws-okta
    steps:
      - checkout
      - run:
          name: Make distributables
          command: |
            make -f Makefile.release dist-windows
      - persist_to_workspace:
          root: .
          paths: ['dist/*']

workflows:
  version: 2
  # currently we only build/publish for linux: macOS builds require non-FOSS
  # Keychain libs that require a macOS host to build on
  # https://github.com/segmentio/aws-okta/issues/81
  test-dist-publish-windows:
    jobs:
      - test-build-golang-prev
      - dist-windows:
          # needed to ensure dist happens on tag events
          filters:
            tags:
              only: /.*/
