version: 2
jobs:
  test-build-golang-prev:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install linux dependencies - libusb
          command: |
            sudo apt update -q
            sudo apt install -yq libusb-dev libusb-1.0.0-dev
      - run:
          name: Test
          command: |
            go build -mod=vendor
            ./aws-okta version
  dist-windows:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/segmentio/aws-okta
    steps:
      - checkout
      - run:
          name: Make distributables
          command: |
            make -f Makefile.release dist-windows
      - persist_to_workspace:
          root: .
          paths: ['dist/*']
  publish-github-windows:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/segmentio/aws-okta
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: 
          name: Install tools
          command: |
            make -f Makefile.tools github-release
            make -f Makefile.release publish-github-windows
workflows:
  version: 2
  test-dist-publish-windows:
    jobs:
      - test-build-golang-prev
      - dist-windows:
          # needed to ensure dist happens on tag events
          filters:
            tags:
              only: /.*/
      - publish-github-windows:
        context: github-dkujawskicircle-oss-release
        requires:
          - dist-windows
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-[a-zA-Z0-9-]+)?/